git:
  depth: 5
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: pedre87@gmail.com
  on:
    branch: master
  api_key:
    secure: 0LmnAahi9ersEYYFWBUfBfAlfk713GZ/0A4yf7I669a9xDCAwMtktifqHrBd8vogoKHrBcCJ7Nrj94RqyhaGWVPOfM7TpFPU3+NtILFh7BRbYCu8XNyzjwrYddHnbjQ9S9a11i66+fc9pfQ+AYB8cwJYFuHoV5M1+biv5AqD4jSuORZaUrqBT/tbUqbQ4KrmjyZ+fEUASDdMfhH+hgHG8KzY2unsrV58GCg+bd2o1w7vgaKIFwrNTwYIuCTSBasxwl2/Fd+9EtxXIKQDsFRUftI9d5zVgYkqnfDo02NlRiyPlPR1403jcZvo1QPAjLf+aElWOvyPigtu5TcdOQZh0DsOKqycI/H6/oXf5EVFbwLAV5sgydf+9EVDB9nZ8YqboIWwgfu1mcVqebrJZCTT4yvHUh7W4DHoWJ33yMkBOec0900HQ82ZP8ROpaqBZ/paQElZDGdfLkW2VfSZYBUiP27HuMW1w7YUaVqBL4+jphcdZz/aMya4AqIUeqJusbeb8sbEznSifMuCZTUjBaOkeylk+NsyLwxGdNuXheRc5VRiA3imz1GlHs8nxKK+v3VXqEiytaJUKohLetFe053FzTJMAiNzfQ6SBDxJnHdqsiHEB7c3/5Vw1r6qcfv3Ug5dXDkgMRXsfkXmu+OVCaXvOY3JdazNrrPn2x+zXncSnKg=
script:
- nohup yarn test
